services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_DATABASE=uso
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    networks:
      - backend

  spring-app:
    build: ./
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:rootpassword@mongodb:27017/uso?authSource=admin
    networks:
      - backend
    depends_on:
      - mongodb

networks:
  backend:
    driver: bridge
