spring:
  application:
    name: uso-bot
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}
owapi:
  base-url: https://owapi.eu
  request-timeout-seconds: 10
discord:
  bot:
    token: ${DISCORD_BOT_TOKEN:}
    guild-ids: [ 1355913961312227549, 1355292916540510259 ]
    auto-role-ids: [ 1416714044995403776, 1355305040058908793 ]
animal-api:
  base-url: https://api.animality.xyz
