name: Build & Release

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean bootJar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: uso-bot
          path: build/libs/uso-bot.jar

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download JAR artifact
        uses: actions/download-artifact@v5
        with:
          name: uso-bot

      - name: Configure Git for tagging
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create Git tag
        run: |
          TAG="v${{ github.run_number }}"
          git tag -a $TAG -m "Release $TAG"
          git push origin $TAG

      - name: Create GitHub Release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836
        with:
          files: uso-bot.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: v${{ github.run_number }}
          RELEASE_NAME: Release v${{ github.run_number }}
          RELEASE_BODY: Automated release of uso-bot version v${{ github.run_number }}
